---
language: python
services: docker

env:
  global:
    - ROLE_NAME: seedbox
  matrix:
    - MOLECULE_DISTRO: debian10
    - MOLECULE_DISTRO: ubuntu2004
    - MOLECULE_DISTRO: ubuntu1804

install:
  - pip install molecule yamllint docker ansible-lint

script:
  - molecule test

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
