---
language: python
python: "2.7"

sudo: false

addons:
  apt:
    packages:
      - python-pip

install:
  - pip install ansible
  - ansible --version

script:
  - ansible-galaxy install geerlingguy.nodejs
  - cd tests/
  - ansible-playbook test.yml -i ./inventory --syntax-check
  - ansible-playbook test.yml -i ./inventory -vv

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/