---
- name: rtorrent | Ensure required groups are present
  group:
    name: "{{ item }}"
    state: present
  loop:
    - rtorrent
    - www-data

- name: rtorrent | Create rtorrent user
  user:
    name: rtorrent
    group: www-data
    password: "{{ rtorrent_user_password }}"
    shell: /bin/bash

- name: rtorrent | Create base directories
  file:
    path: "/home/rtorrent/{{ item }}"
    state: directory
  loop: 
    - upload
    - download
    - .session
    - logs
  become_user: rtorrent
  
- name: rtorrent | Copy .rtorrent.rc configuration file
  template: 
    src: .rtorrent.rc.j2
    dest: /home/rtorrent/.rtorrent.rc
    owner: rtorrent
    group: www-data
    mode: 0775

- name: rtorrent | Copy systemd unit
  template:
    src: rtorrent.service.j2
    dest: /etc/systemd/system/rtorrent.service

- name: rtorrent | Enable and start service
  systemd:
    name: rtorrent
    state: started
    enabled: yes
    daemon_reload: yes

- name: Wait for SCGI port
  wait_for:
    port: "{{ rtorrent_network_scgi_open_port }}"
    delay: 5
    timeout: 30
